### PR TITLE
Tried adding the extra types

### PR DESCRIPTION
**Pull request by stygiansabyss**
- Added operator type class
- Added missing operator keys to statistics type class

addresses #2

### CODE REVIEW

**Comment by Korbeil** [comment]
Thanks ! Sorry for not answering, I'll check the PR tomorrow, I also need to see why tests are failing :/

**Comment by stygiansabyss** [comment]
It failed from `unknown status code` error.

**Comment by Korbeil** [comment]
Thanks @stygiansabyss !

**Comment by stygiansabyss** [comment]
Np.  If you make issues for some of the other changes you want to make on the repo I will try to help get through them.

**Pull request merged**
